"""Synthetic multimodal content: shape in, real containers out.

Two properties matter and neither is visible from the trace alone, so these
tests measure what the server actually receives: that the generated bytes are
the size the manifest promised, and that content uniqueness follows the seed.
"""

from __future__ import annotations

import itertools
import json
import subprocess
import sys
import time
from pathlib import Path

import pytest

from benchmarks.__main__ import main as benchmark_main

REPO_ROOT = Path(__file__).resolve().parents[1]

PREFLIGHT_ID = "req-frontend-preflight"


def workload_rows(log: Path) -> list[dict]:
    """Server-side rows for the measured workload only.

    A multimodal run is preceded by preflight probes -- one with media and one
    without -- which the server logs like any other request. They are not the
    workload and would otherwise be read as its first rows.
    """
    return [
        row
        for row in (json.loads(line) for line in log.read_text().splitlines())
        if row.get("request_id") != PREFLIGHT_ID
    ]



def _materialize(tmp_path: Path, *extra: str) -> tuple[Path, dict]:
    out = tmp_path / "syn"
    assert (
        benchmark_main(["synthetic", "--output-dir", str(out), *extra]) == 0
    ), "materializer failed"
    manifest = json.loads((out / "manifest.json").read_text())
    return out / "requests.jsonl", manifest


def _serve(tmp_path: Path, dialect: str = "vllm-omni"):
    ready = tmp_path / "ready"
    log = tmp_path / "server.jsonl"
    process = subprocess.Popen(
        [
            sys.executable,
            str(REPO_ROOT / "tools" / "mock_multimodal_server.py"),
            "--dialect", dialect,
            "--ready-file", str(ready),
            "--log-path", str(log),
        ],
        cwd=REPO_ROOT, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
    )
    deadline = time.monotonic() + 15
    while time.monotonic() < deadline and not ready.exists():
        if process.poll() is not None:
            raise AssertionError(process.stderr.read())
        time.sleep(0.05)
    assert ready.exists(), "mock did not become ready"
    return process, int(ready.read_text()), log


def _replay(tmp_path: Path, trace: Path, port: int, name: str) -> dict:
    summary = tmp_path / f"{name}-summary.json"
    completed = subprocess.run(
        [
            str(REPO_ROOT / "target" / "debug" / "session_runner"),
            "--trace", str(trace),
            "--input-file-format", "multimodal-independent-v1",
            "--base-url", f"http://127.0.0.1:{port}/v1",
            "--backend", "openai-chat",
            "--dialect", "vllm-omni",
            "--model", "m",
            "--arrival-mode", "saturated",
            "--max-concurrency", "2",
            "--timeline", "false",
            "--summary-path", str(summary),
            "--log-path", str(tmp_path / f"{name}-requests.jsonl"),
        ],
        cwd=REPO_ROOT, capture_output=True, text=True, timeout=60, check=False,
    )
    assert completed.returncode == 0, completed.stderr
    return json.loads(summary.read_text())["replay"]["common"]


@pytest.fixture(scope="module", autouse=True)
def _built() -> None:
    subprocess.run(
        ["cargo", "build", "--bin", "session_runner"],
        cwd=REPO_ROOT, check=True, capture_output=True, text=True,
    )


def test_the_trace_declares_shape_not_content(tmp_path: Path) -> None:
    """A trace describing megabytes of media stays kilobytes on disk."""
    trace, manifest = _materialize(
        tmp_path, "--count", "50", "--modality", "image", "--width", "512", "--height", "512"
    )
    per_request = manifest["generated"]["bytes_per_request"]
    assert per_request > 700_000, "512x512 RGB is most of a megabyte"
    assert trace.stat().st_size < 20_000, "the trace itself stays small"
    rows = workload_rows(trace)
    assert len(rows) == 50
    assert rows[0]["inputs"][0]["synthetic"] == {"width": 512, "height": 512}


def test_arrival_rate_sets_the_declared_spacing(tmp_path: Path) -> None:
    trace, manifest = _materialize(tmp_path, "--count", "5", "--arrival-rate", "20")
    rows = workload_rows(trace)
    spacing = [
        round(b["arrival_time_ms"] - a["arrival_time_ms"], 3) for a, b in itertools.pairwise(rows)
    ]
    assert spacing == [50.0] * 4
    assert manifest["request"]["arrival_rate_per_s"] == 20


@pytest.mark.parametrize(
    ("modality", "flags"),
    [
        ("image", ["--width", "48", "--height", "32"]),
        ("audio", ["--sample-rate-hz", "16000", "--duration-ms", "250"]),
        ("video", ["--width", "32", "--height", "32", "--frames", "4"]),
    ],
)
def test_generated_size_is_exactly_what_the_manifest_promised(
    tmp_path: Path, modality: str, flags: list[str]
) -> None:
    """The predicted size and the generator must not drift apart.

    The manifest is how an operator sizes a run before making it, so it is
    checked against the bytes the server actually receives rather than against
    a second copy of the same arithmetic.
    """
    trace, manifest = _materialize(
        tmp_path, "--count", "2", "--modality", modality, "--content-seed", "5", *flags
    )
    process, port, log = _serve(tmp_path)
    try:
        result = _replay(tmp_path, trace, port, modality)
    finally:
        process.terminate()
        process.wait(timeout=10)
    assert result["success_steps"] == 2 and result["failed_steps"] == 0

    rows = workload_rows(log)
    assert len(rows) == 2
    assert all(row["media_bytes"] == manifest["generated"]["bytes_per_request"] for row in rows)


def test_a_pinned_seed_sends_identical_content_and_omitting_it_does_not(
    tmp_path: Path,
) -> None:
    pinned = tmp_path / "pinned"
    pinned.mkdir()
    trace, _ = _materialize(
        pinned, "--count", "3", "--width", "32", "--height", "32", "--content-seed", "11"
    )
    process, port, log = _serve(pinned)
    try:
        assert _replay(pinned, trace, port, "pinned")["success_steps"] == 3
    finally:
        process.terminate()
        process.wait(timeout=10)
    digests = {row["media_sha256"] for row in workload_rows(log)}
    assert len(digests) == 1, "a pinned seed means non-unique content"

    unique = tmp_path / "unique"
    unique.mkdir()
    trace, _ = _materialize(unique, "--count", "3", "--width", "32", "--height", "32")
    process, port, log = _serve(unique)
    try:
        assert _replay(unique, trace, port, "unique")["success_steps"] == 3
    finally:
        process.terminate()
        process.wait(timeout=10)
    digests = {row["media_sha256"] for row in workload_rows(log)}
    assert len(digests) == 3, "without a seed each request carries its own content"


def test_generated_media_is_a_real_container_the_server_can_parse(tmp_path: Path) -> None:
    """The mock decodes what it receives, so a malformed container would 400.

    This is the reason the generator writes real PNG and WAV rather than random
    bytes: a server that decodes its inputs would otherwise measure error
    handling instead of inference.
    """
    trace, _ = _materialize(
        tmp_path, "--count", "1", "--modality", "image", "--width", "16", "--height", "16"
    )
    process, port, log = _serve(tmp_path)
    try:
        assert _replay(tmp_path, trace, port, "container")["success_steps"] == 1
    finally:
        process.terminate()
        process.wait(timeout=10)
    row = workload_rows(log)[0]
    assert row["media_parts"] == 1
    assert row["text_parts"] == 1


def test_a_shape_the_generator_cannot_build_is_rejected_at_load(tmp_path: Path) -> None:
    trace = tmp_path / "bad.jsonl"
    trace.write_text(
        json.dumps(
            {
                "id": "bad-0",
                "arrival_time_ms": 0.0,
                # An image with no dimensions: nothing to generate.
                "inputs": [{"type": "image", "synthetic": {"seed": 1}}],
                "outputs": [{"type": "text", "max_tokens": 4}],
            }
        )
        + "\n"
    )
    completed = subprocess.run(
        [
            str(REPO_ROOT / "target" / "debug" / "session_runner"),
            "--trace", str(trace),
            "--input-file-format", "multimodal-independent-v1",
            "--base-url", "http://127.0.0.1:9/v1",
            "--backend", "openai-chat", "--dialect", "vllm-omni", "--model", "m",
            "--arrival-mode", "saturated",
            "--summary-path", str(tmp_path / "s.json"),
        ],
        cwd=REPO_ROOT, capture_output=True, text=True, timeout=60, check=False,
    )
    assert completed.returncode != 0
    assert "requires positive width and height" in completed.stderr
    assert not (tmp_path / "s.json").exists(), "nothing should have run"
